"""CLI of the dev install flow: argument parsing and dispatch for install.py.

Only the dev flow (``install.py --home/--yes/--uninstall``) goes through
this module; the launcher's ``modus-operandi`` console script lives in cli.py.

The dev flow renders the pipeline from the checkout and, so the command
works in every newly opened terminal, also installs a checkout-based
``modus-operandi`` launcher into ``~/.local/bin`` and keeps that directory on
PATH in the user's shell rc files (the pip model's console script already
lands there via ``pip install --user``).
"""

from __future__ import annotations

import argparse
import os
import sys
from collections.abc import Sequence
from pathlib import Path

from . import InstallError, Paths, installer, paths, uninstall

# The package checkout this dev flow installs from (installer_cli.py lives at
# <repo>/src/modus_operandi/): the launcher references the checkout's src/
# directory so the rendered dev artifacts and the command stay in sync.
_REPO_SRC = Path(__file__).resolve().parent.parent

_LAUNCHER = """#!/usr/bin/env python3
# Generated by install.py (dev flow): runs the modus-operandi launcher from
# the checkout sources. Re-run `python3 install.py` after moving the checkout.
import sys
from pathlib import Path

sys.path.insert(0, "{src_dir}")

from modus_operandi.cli import main

if __name__ == "__main__":
    sys.exit(main())
"""

# The PATH block appended to the existing shell rc files (idempotent marker).
_RC_MARKER = "# --- modus-operandi: keep the launcher bin dir on PATH ---"
_RC_BLOCK = (
    _RC_MARKER + "\n"
    'case ":$PATH:" in *:"$HOME/.local/bin":*) ;; *) export PATH="$HOME/.local/bin:$PATH" ;; esac\n'
)
_RC_FILES = (".bashrc", ".zshrc", ".profile")


def _render_launcher(layout: Paths) -> bool:
    """Install the checkout-based launcher into ~/.local/bin.

    Returns True when the launcher was written; a pip-owned console script
    (``pip install --user modus-operandi``) is kept as-is — it is the same
    file path, and overwriting it would leave the pip metadata pointing at
    foreign content.
    """
    target = layout["user_bin"] / "modus-operandi"
    if target.resolve() in uninstall.pip_installed_bin(layout):
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_LAUNCHER.format(src_dir=_REPO_SRC), encoding="utf-8")
    target.chmod(0o755)
    return True


def _ensure_bin_on_path(layout: Paths) -> list[str]:
    """Keep ~/.local/bin on PATH in the existing shell rc files.

    The installer never creates shell configs: files that already exist
    (~/.bashrc, ~/.zshrc, ~/.profile) get the guarded export appended once
    (the marker makes re-runs a no-op). Returns the rc files that were
    patched.
    """
    home = layout["user_bin"].parent.parent
    patched: list[str] = []
    for name in _RC_FILES:
        rc = home / name
        if not rc.is_file():
            continue
        text = rc.read_text(encoding="utf-8")
        if _RC_MARKER in text:
            continue
        if text and not text.endswith("\n"):
            text += "\n"
        rc.write_text(text + _RC_BLOCK, encoding="utf-8")
        patched.append(f"~/{name}")
    return patched


def print_instructions(layout: Paths) -> None:
    print(
        "\nDone. Next steps:\n"
        "  1. Edit {} to choose your models "
        "(planner = strong, executor = cheap), then rerun install.py, or\n"
        "     re-apply the changes in one go with `modus-operandi edit`.\n"
        "  2. In any project run (no `specify init` required):\n"
        '       modus-operandi task "your task description"\n'
        "     or review your code (default: whole codebase):\n"
        "       modus-operandi review\n"
        "     or review only the changes between branches:\n"
        "       modus-operandi review --branch-diff\n"
        "     or open the installed config in your editor and apply it on exit:\n"
        "       modus-operandi edit\n"
        "  3. If the run pauses at a gate, review and resume with:\n"
        "       specify workflow resume <run_id>\n".format(layout["config"])
    )


def dispatch(args: argparse.Namespace) -> int:
    home = Path(args.home).expanduser() if args.home else Path.home()
    layout = paths.build_paths(home)
    if args.uninstall:
        return uninstall.do_uninstall(layout, args.yes)
    print("modus-operandi installer")
    created, _ = installer.install(layout)
    if created:
        print(f"created {layout['config']} with defaults (edit it to change models)")
    print("installation verified")
    if _render_launcher(layout):
        print("installed the 'modus-operandi' command to ~/.local/bin/modus-operandi")
    else:
        print("kept the pip-installed 'modus-operandi' console script in ~/.local/bin")
    patched = _ensure_bin_on_path(layout)
    for rc in patched:
        print(f"added ~/.local/bin to PATH in {rc} (new terminals only)")
    if not patched and str(layout["user_bin"]) not in os.environ.get("PATH", "").split(os.pathsep):
        print(
            "\nwarning: ~/.local/bin is not on your PATH - add it (e.g. "
            'export PATH="$HOME/.local/bin:$PATH") or call the launcher by '
            "its full path"
        )
    print_instructions(layout)
    return 0


def parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Install the modus-operandi planner/executor pipeline (dev flow)"
    )
    parser.add_argument("--uninstall", action="store_true", help="remove installed files")
    parser.add_argument(
        "--home",
        metavar="DIR",
        help="base directory instead of the real home (used by tests)",
    )
    parser.add_argument("--yes", action="store_true", help="answer yes to all prompts")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    # YAML parse errors are already wrapped into InstallError by
    # config.load_config; everything else here is a user-facing failure.
    try:
        args = parse_args(argv)
        return dispatch(args)
    except (InstallError, OSError, ValueError, KeyError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        # Ctrl+C at a prompt (e.g. the uninstall confirmation) is a normal
        # way to bail out: a quiet exit 130, not a traceback.
        print("interrupted", file=sys.stderr)
        return 130
